# Generated by Django 4.1.5 on 2023-06-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='number',
        ),
    ]
